require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegistriesController do

  # This should return the minimal set of attributes required to create a valid
  # Registry. As you add validations to Registry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all registries as @registries" do
      registry = Registry.create! valid_attributes
      get :index
      assigns(:registries).should eq([registry])
    end
  end

  describe "GET show" do
    it "assigns the requested registry as @registry" do
      registry = Registry.create! valid_attributes
      get :show, :id => registry.id.to_s
      assigns(:registry).should eq(registry)
    end
  end

  describe "GET new" do
    it "assigns a new registry as @registry" do
      get :new
      assigns(:registry).should be_a_new(Registry)
    end
  end

  describe "GET edit" do
    it "assigns the requested registry as @registry" do
      registry = Registry.create! valid_attributes
      get :edit, :id => registry.id.to_s
      assigns(:registry).should eq(registry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Registry" do
        expect {
          post :create, :registry => valid_attributes
        }.to change(Registry, :count).by(1)
      end

      it "assigns a newly created registry as @registry" do
        post :create, :registry => valid_attributes
        assigns(:registry).should be_a(Registry)
        assigns(:registry).should be_persisted
      end

      it "redirects to the created registry" do
        post :create, :registry => valid_attributes
        response.should redirect_to(Registry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registry as @registry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        post :create, :registry => {}
        assigns(:registry).should be_a_new(Registry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        post :create, :registry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested registry" do
        registry = Registry.create! valid_attributes
        # Assuming there are no other registries in the database, this
        # specifies that the Registry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Registry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => registry.id, :registry => {'these' => 'params'}
      end

      it "assigns the requested registry as @registry" do
        registry = Registry.create! valid_attributes
        put :update, :id => registry.id, :registry => valid_attributes
        assigns(:registry).should eq(registry)
      end

      it "redirects to the registry" do
        registry = Registry.create! valid_attributes
        put :update, :id => registry.id, :registry => valid_attributes
        response.should redirect_to(registry)
      end
    end

    describe "with invalid params" do
      it "assigns the registry as @registry" do
        registry = Registry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        put :update, :id => registry.id.to_s, :registry => {}
        assigns(:registry).should eq(registry)
      end

      it "re-renders the 'edit' template" do
        registry = Registry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        put :update, :id => registry.id.to_s, :registry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested registry" do
      registry = Registry.create! valid_attributes
      expect {
        delete :destroy, :id => registry.id.to_s
      }.to change(Registry, :count).by(-1)
    end

    it "redirects to the registries list" do
      registry = Registry.create! valid_attributes
      delete :destroy, :id => registry.id.to_s
      response.should redirect_to(registries_url)
    end
  end

end
